### ISSUE TITLE
大佬，求删除关于字节360部分的内容

### ISSUE THREAD

**Issue by LampScript** [linonetwo/template-based-generator-template#2]
我看了下文案，是我之前写的内容，后来我被公司OC和绩效薪酬的同学分别约谈了，他们的语气很重。。。趁着还没传播开来之前，求删除这部分代码

**Comment by LampScript** [comment]
愿以联系的话可以加我微信：cybyte_2049

**Comment by LampScript** [comment]
我的文案也提交给薪酬同学了，如果有真的在绩效里使用的话会有很大的问题的

**Comment by linonetwo** [comment]
OK，已删除

**Comment by linonetwo** [comment]
没搜到你这个微信号，估计你也离职了，应该也不在意了，我今天要用这个模板，就先恢复了
